### ISSUE TITLE
dynamic navigation does not work with cargo

### ISSUE THREAD

**Issue by ThomasSchoeller** [thaider/Tweeki#101]
I tried building a dynamic menu as in https://tweeki.thai-land.at/wiki/MediaWiki:Tweeki-navbar-left with cargo instead of SME.

<img width="766" alt="tweeki cargo query" src="https://user-images.githubusercontent.com/19622606/35782000-d2c35f20-09f1-11e8-8915-c9268b8a3a40.png">
tried different lists "styles"...
<img width="750" alt="tweeki cargo query 2" src="https://user-images.githubusercontent.com/19622606/35782002-d6196fd4-09f1-11e8-842d-bc989ee14264.png">

<img width="868" alt="tweeki cargo query 3" src="https://user-images.githubusercontent.com/19622606/35782003-d8a786c8-09f1-11e8-8d92-b3313bf311ce.png">

Someone Using tweeki with cargo?

**Comment by thaider** [comment]
Hi. Cargo is currently not supported, sorry. It shouldn't be very hard to implement but it won't be done by me because I don't use Cargo myself. I'll happily accept any working patches, though. Have a look at the [source code](https://github.com/thaider/Tweeki/blob/master/Tweeki.hooks.php#L293) to get an idea of what would be necessary to make it work.
