### ISSUE TITLE
MultiLevel dropdown

### ISSUE THREAD

**Issue by TheSin-** [thaider/Tweeki#103]
More a feature, our menus are very large, was wondering if we could build multi tier menu systems with something like 

Menu
* Item1
** Item1-1
** item1-2
* Item2

I haven't even looked into it so I'm not sure how much work it would be, But figured I'd post incase.

**Comment by thaider** [comment]
Tweeki's functionality is limited in this regard as to what is possible with Bootstrap. Older versions of the framework hat multiple levels but it's not supported anymore. I can imagine it's because of it's mobile-first approach. Multi-level dropdowns usually don't work so well on small screen sizes. Maybe using the sidebar or the sub navigation could be a solution for you?

**Comment by TheSin-** [comment]
Thanks for the explanation and that totally makes sense.  Thanks for the great theme I'll have to figure something out for sure.

There is one more tiny bug that I just had to deal with on an other site with a static top menu, if the menu ends up wrapping do to smaller screen size then expected, it coves part of the content, the underlaying div needs to grow as the static on does and match it's size.  Or you can take a full css approach and not use static at all and use transform on scroll, it makes the menu a little jerky but you don't need js at all then.  Anyhow thought you'd like to know about.

**Comment by thaider** [comment]
Thanks for reporting. I'm not sure I completely understand the problem you describe. Could you provide some screenshots to illustrate what you're talking about?

**Comment by TheSin-** [comment]
sure, the first one is proper, the second one I made my browser window smaller, see how the menu bar grows but the underlaying content doesn't move down, that is do to using static, and the spacing you have in the content pain doesn't move with it.  It's a common issue, as mentioned I just dealt with it on an other site I maintain.

![screen shot 2018-02-12 at 7 41 38 am](https://user-images.githubusercontent.com/1868661/36102028-39b604d6-0fc8-11e8-8535-ce5a91b3a7ff.png)
![screen shot 2018-02-12 at 7 41 22 am](https://user-images.githubusercontent.com/1868661/36102032-3e31f6e6-0fc8-11e8-9b44-e0cb629ff5c1.png)

**Comment by thaider** [comment]
Hi. Thanks for the images, I can see now what you're referring to. I was confused by your use of the word 'static', because what your images are showing is a fixed navbar (in contrast to a static navbar that would move with the content when scrolling). 

I'm not sure, if you know it, but if you want to use a static navbar with Tweeki you can just change the content of `MediaWiki:Tweeki-navbar-class` from `navbar navbar-default navbar-fixed-top` to `navbar navbar-default`. 

The problem occurs when the breakpoint for the collapsing of the navbar does not align with the actual width of the navbar's content. So another approach would be to change this breakpoint, either by overwriting the relevant css rules or using your own [customized bootstrap files](https://getbootstrap.com/docs/3.3/customize/).

**Comment by TheSin-** [comment]
oh I see, not sure why I always refer to them as static, but you are right the css tag for it is fixed.

oh I know how to fix it, I'm not worried about thought you might want to build a fix into the theme so hated to make you aware is all.

Again thanks for the great theme!
