### ISSUE TITLE
XSS vulnerability in Search field, not otherwise present in MediaWiki

### ISSUE THREAD

**Issue by npdoty** [thaider/Tweeki#104]
https://tweeki.thai-land.at/w/index.php?search=1%22%3E%3Cscript%3Ealert(150)%3C/script%3E&go=Go causes an alert to fire on the visitor's machine. This should not be possible because the search box should sanitize input. 

MediaWiki without this skin installed correctly sanitizes the input.

Apologizes for filing security bug in this public way, but not sure other ways to contact the developers. This bug can be found and is being found through automated testing.

**Comment by npdoty** [comment]
Bug is on this line, although it's possible that other data is also not being properly escaped:
https://github.com/thaider/Tweeki/blob/master/Tweeki.skin.php#L1110

`$this->data['search']` is being concatenated into the text of the page without escaping. Either needs to be changed to `$this->html` or be wrapped in `htmlspecialchars( $string, ENT_QUOTES )`.

**Comment by thaider** [comment]
Thanks a lot for reporting and providing a patch. The bug was already present in the strapping skin (which was the starting point for Tweeki) – it just found out, that it was fixed there shortly after my fork ([see commit](https://github.com/OSAS/strapping-mediawiki/commit/5b563c45ad7b02c66ae77f0f7f4985654ee36644#diff-111ad4a76ab8122fe8e1d28f078de562)), I could have seen that :(
