### ISSUE TITLE
Is there someway I can customize the right side bar so that only the TOC appears on one page and only MYNAV appears on another?

### ISSUE THREAD

**Issue by zhangx20** [thaider/Tweeki#115]

**Comment by thaider** [comment]
There are several possible solutions to achieve this:
- For MYNAV (custom Navigational or Special Elements) you have all the control you could possibly want because you can put any check in the callback function that you define. See [the documentation](https://tweeki.thai-land.at/wiki/How-Tos#Show_or_hide_navigational_elements_depending_e.g._on_category) for an example of showing an element only on pages that belong to a certain category.
- You could show/hide navigational elements using CSS and use the [`{{#tweekibodyclass}}`](https://tweeki.thai-land.at/wiki/Parser_Functions#Tweekibodyclass_parser_function) parser function as a behaviour switch. Example: add `{{#tweekibodyclass:show-mynav}}` to the page where MYNAV should be shown, apply the class `mynav` to MYNAV and use the following CSS rules:

```
.mynav { display:none; }
.show-mynav .mynav { display:block; }
```
