### ISSUE TITLE
Dropdowns render wrongly when using pipe in parent

### ISSUE THREAD

**Issue by mir123** [thaider/Tweeki#158]
I'm setting up a dropdown nav element, where the parent is MyLink|Mytext. I set up my dropdown as *Mydropdown. The dropdown is then rendered below the parent, with the effect of the navbar being twice as high and the arrow being below the parent on the left instead of next to the parent on the right. ![Screenshot_tweeki_navbar_error](https://user-images.githubusercontent.com/907400/80281523-53c61a00-86d1-11ea-8bfe-ce00c0a44426.png)

**Comment by thaider** [comment]
Hi. Thanks for reporting. Please note that using the pipe here creates a [split dropdown](https://tweeki.kollabor.at/wiki/Buttons#Dropdown_Buttons). Boostrap doesn't support split dropdowns in the navigation. Are you sure you want “Siempreshoy” to be a link to a page instead of toggling the dropdown?
