### ISSUE TITLE
Uses `User::getEffectiveGroups`

### ISSUE THREAD

**Issue by kghbln** [thaider/Tweeki#213]
This will probably be hard deprecated in MediaWiki 1.37 I assume. See the respective [phabricator task](https://phabricator.wikimedia.org/T275148).

**Comment by IEatApples** [comment]
Yes. I noticed Tweeki was marked as 'unstable' on it's [Mediawiki page](https://www.mediawiki.org/wiki/Skin:Tweeki) because of this issue.

I would like to upgrade my current versions of Tweeki 1.1.1 and Mediawiki 1.35.0.

Do you know the most current versions of Tweeki and Mediawiki combination that are stable?

**Comment by IEatApples** [comment]
Thanks!

**Comment by thaider** [comment]
Thanks for reporting, should be fixed now.
