### ISSUE TITLE
TOC links don't expand correctly with top nav

### ISSUE THREAD

**Issue by mestela** [thaider/Tweeki#255]
Hi, I love the look and feel of tweeki, but noticed an issue with the dynamically expanding TOC and the top nav. If you follow this link for example:

https://www.tokeru.com/cgwiki/PopsSplitAvoid#Grid_noise

You'll see that it links to the right place, and the title is visible, which I've done by adding 

```
.mw-headline {
    scroll-margin-top: 4rem;
}
```

To my tweeki.css. The TOC is incorrect though, it is highlighting the previous section. If you scroll down a little so that the 'Grid noise' title hits the top of the page under the top nav, then the TOC expands as expected.

Is there a way to apply a similar 'scroll-margin-top' fix to the TOC expand code, so the correct sections expand a little earlier, not just when they hit the top of the page underneath the top nav?

**Comment by thaider** [comment]
Should be fixed in latest master. In order to make it work, you should remove your custom stylings for `.mw-headline` and instead set the top padding for the content to the right value:

```
.with-navbar.with-navbar-fixed {
  padding-top: 4rem !important;
}
```

Some newly added javascript will read this value and use it as offset for the scrollspy feature that is responsible for expanding the toc at the correct position.

**Comment by mestela** [comment]
Oh awesome, thanks!
