### ISSUE TITLE
QQX broken

### ISSUE THREAD

**Issue by aquatiki** [thaider/Tweeki#53]
Unable to use the standard trick of appending "&uselang=qqx" to the URL in order to find out which of Mediawiki:AllMessages are being used for various aspects of the interface.  (Try it on another skin and you'll see what I mean.)
![image](https://cloud.githubusercontent.com/assets/10630623/8159584/b8c050a0-132d-11e5-8522-8fc9b6a7e712.png)

**Comment by thaider** [comment]
Thanks for your comment. This is my first published project and I'm thankful for any feedback. I'm not sure if I understand your issue correctly. Tweeki uses system messages to customize the navigational sections (like navbar, sidebar, footer, etc.). The contents of the sections can contain system messages themselves. They can for example contain 
* standard navigational elements (e.g. "FOOTER", the standard contents of the footer, which is partly customizable via messages) 
* some button markup (if the markup for the link text or the target equals the name of message it will be replaced, e.g. "mainpage" would become "Main Page" - I just found out that this feature hadn't been documented yet)
The qqx trick only shows the first unexpanded level of messages. If it is your concern to find out the name of one particular standard system message in order to customize the interface you will have to use another skin or refer to mediawiki.org for example. 

Please let me know if my explanation helps...

**Comment by aquatiki** [comment]
You're explanation does help.  I'm customizing a lot, so I use that trick daily, but your awesome skin is worth a work around! :-)
