### ISSUE TITLE
Unable to edit navbar stuff for non-anon

### ISSUE THREAD

**Issue by aquatiki** [thaider/Tweeki#54]
Is there no way to edit the menus for non-anonymous users?  This seems like a bug, to step down by logging in, or at least, to have it be un-customizable.
![image](https://cloud.githubusercontent.com/assets/10630623/8159635/376c7974-132e-11e5-8415-d03ef5f15ec9.png)

**Comment by thaider** [comment]
Thanks for your comment. It is quite possible that there are some bugs around. Could you elaborate a bit what you're trying to achieve? Editing of system messages is typically restricted to sysops with the [editinterface](https://www.mediawiki.org/wiki/Editinterface) permission. You can enable it for all non-anonymous users with the following line in LocalSettings.php:
$wgGroupPermissions['user']['editinterface'] = true;

If I read your screenshot correctly, tweeki-navbar-left is not working the way it should. Could you try to find out where the problem lies (charset?)? However, only one sublevel is supported in the navigation ("\*\*HSK/1" will be parsed as if you had written "*HSK/1")...

**Comment by aquatiki** [comment]
From what I can tell, editing the system messages via the Mediawiki pages you describe on your website only affects anonymous users.  Here's how it looks to anonymous:
![image](https://cloud.githubusercontent.com/assets/10630623/8245162/08aae8d6-15f0-11e5-93d1-31c14b152111.png)

**Comment by thaider** [comment]
That's weird. Maybe it is some strange caching problem? Could you try checking that? What are the values of your $wgTweekiSkinHide* variables? User aquatiki has chosen the 'show advanced features' preference, right?

**Comment by aquatiki** [comment]
yes, Aquatiki has "show advanced features".  I've cleared the cache completely several times.  $wgTweekiSkinHideAnon = array('sidebar'); 
&wgTweekiSkinHideable = ('firstHeading','sidebar','subnav');

**Comment by thaider** [comment]
I won't have the chance to investigate it further before next week. A thought that came up is, that it could have to do with language settings. Is Aquatiki's language preference setting different from the setting in LocalSettings.php? This could explain why after logging in the English default messages are being used...

**Comment by aquatiki** [comment]
That was it!  As you can see, I'm creating a multi-lingual site, so it would be enormously helpful if people could sign in via their own language.  Why does that change Mediawiki:Tweaki-subnav?

**Comment by thaider** [comment]
I don't have much experience with multilingual mediawiki sites. If you want to make it possible for registered users to use a different interface language you should edit the English versions of system messages (i.e. Mediawiki:Tweeki-subnav/en instead of Mediawiki:Tweeki-subnav), because English is the ultimate fallback language if no localized version exists. If the navigational sections should be different for every language you can explicitly set it by creating additional subpages with the respective language codes. The base page will always be interpreted as containing the message for the site's language (as set in LocalSettings.php with [wgLanguageCode](https://www.mediawiki.org/wiki/Manual:$wgLanguageCode)).
If you want to have a multilingual experience also for anonymous users, [Extension:LanguageSelector](https://www.mediawiki.org/wiki/Extension:LanguageSelector) could be interesting for you...

**Comment by aquatiki** [comment]
Got it.  Thanks!

**Comment by vlasvlasvlas** [comment]
Hi! got the same error here.. ..

what the solution for this double search-bar effect?


![10-07-2015 17-48-51](https://cloud.githubusercontent.com/assets/4071796/8628760/fd19ec86-272b-11e5-9347-462b83ff0e71.png)

**Comment by thaider** [comment]
There are several solutions:
* You can edit __MediaWiki:Tweeki-navbar-right__ to remove the search field from the (upper) navbar.
* You can edit __MediaWiki:Tweeki-subnav__ to remove the search field from the (lower) sub navigation. This one is a bit special, because the default content of the sub navigation is `SIDEBAR`, i.e. the content of MediaWiki:Sidebar. So you can either change MediaWiki:Tweeki-subnav or remove `SEARCH` from MediaWiki:Sidebar.
* You can __hide__ the sub navigation by setting MediaWiki:Tweeki-subnav to `-`.
* You can hide either the navbar (or parts of it) or the sub navigation for everybody or just for anonymous users using `$wgTweekiSkinHideAll` or `$wgTweekiSkinHideAnon` in __LocalSettings.php__ (this comes handy especially for wiki-as-a-website projects - e.g. Tweeki's [documentation](http://tweeki.thai-land.at) uses `$wgTweekiSkinHideAnon = array( 'navbar' );` to hide the navbar for anonymous users).

**Comment by vlasvlasvlas** [comment]
Nice. thanks first option worked for me :)
