### ISSUE TITLE
Images and tables are not responsive

### ISSUE THREAD

**Issue by Tolvic** [thaider/Tweeki#61]
Under the bootstrap framework, I believe that this would only require adding class="img-responsive" to images and class="table-responsive" to tables. I am still very much a newbie to development so it may not be that simple. I can't figure out how these elements are being rendered so I have not been able to try this myself.

**Comment by thaider** [comment]
Could you specify which images you would like to see being responsive? Are you're talking about images that you uploaded yourself and include on a page using the `[[File:Filename.jpg]]` syntax? If so, did you notice this syntax allows for a class option? So you could just use `[[File:Filename.jpg|class=img-responsive]]` to get the desired effect. 

Likewise, for a table you can always just wrap it in a container (e.g. a div) with the `.table-responsive` class.

**Comment by Tolvic** [comment]
Hi, 

Thank you for your quick reply! 

Yes, they were the images that I was referring to and I was not aware of that. Thank you for pointing it out; that works. Is it possible to have this class applied to all images automatically? Two reasons: 1) it relies on users to add this syntax to images, 2) images on auto generated pages such as /file:image_name.jpg will not be responsive (I believe).

In regards to tables, would a user editing a page be able to wrap a table in a div? For the same two reasons as before, is it possible to have this class applied to all tables automatically?

Thank you
Terry

**Comment by thaider** [comment]
Yes, it's fairly easy to apply responsitivity to all images automatically. You just have to add the `.img-responsive` class' stylings to the `img` tag. The most simple option should be to just add the following code to `MediaWiki:Custom.css`:

    img {
        display: block;
        max-width: 100%;
        height: auto;
    }

See [Add custom CSS](http://tweeki.thai-land.at/wiki/How-Tos#Add_custom_CSS) in the Tweeki documentation for another more advanced possibility.

(I haven't tested this and applying `display:block` to all images could have unintended consequences for auto generated images at some places.)

For the responsive tables it's not so easy as the class normally needs to be applied to a wrapper (i.e. you need additional html). You would have to dig into bootstrap's stylings to find out if it is possible to duplicate the behaviour without a wrapper. I'm not sure whether or not the responsiveness depends on other bootstrap table classes being applied? Note also that responsiveness for tables doesn't work on all browsers out of the box (see bootstrap documentation). On a case by case basis it's perfectly possible for every (tech savvy) user to add a div wrapper like this (you could also use html table syntax instead of wiki markup):

    <div class="table-responsive">
    {| class="table table-bordered"
    table content
    |}
    </div>
