### ISSUE TITLE
Is there any way to create a multilevel dropdown menu?

### ISSUE THREAD

**Issue by serralex** [thaider/Tweeki#65]
I want to create a menu with 3 levels like the following one. Is it currently possible? Thank you in advance

http://bootsnipp.com/snippets/featured/multi-level-dropdown-menu-bs3

**Comment by thaider** [comment]
The multilevel dropdown was supported in Bootstrap 2 but was dropped in Bootstrap 3. I suppose it is due to Bootstrap's “responsive, mobile first” approach and long multilevel menus aren't really a pleasure to use on smaller devices. I do not intend to support it with Tweeki. If you still want to use it, you can use the `$wgTweekiSkinSpecialElements` global variable to define your own special element to be used in navigational sections like the navbar.

Place this code in your LocalSettings.php or in your own extension:

```php
$wgTweekiSkinSpecialElements['MULTILEVEL'] = multilevelDropdown;
function multilevelDropdown( $skin, $context ) {
  $html = "Insert your dropdown's HTML code here...";
  echo $html;
}
```

and add `MULTILEVEL` to the navigational section where you would like it to appear (e.g. in `MediaWiki:tweeki-navbar-left`). For adding the CSS you have several options in MediaWiki, the easiest being `MediaWiki:common.css` (but be aware that it's not loaded on the login and preferences pages!).

**Comment by ValentinaRodrigues** [comment]
@thaider
Can you give an example of customized element for wgTweekiSkinSpecialElements?
