### ISSUE TITLE
IE 11 cannot load the Bootstrap less file

### ISSUE THREAD

**Issue by pixuenan** [thaider/Tweeki#79]
Hi Thaider,

Seems IE 11 cannot load the Bootstrap less files in the components folder. For example, in the sidebar.less file, the 'position' of '.sidebar-wrapper' is set to 'static', so the TOC will go to the bottom of the page. In Chrome and Firefox it works, except in IE 11. May I know is there any way to fix the problem?

Regards,

Xuenan

**Comment by thaider** [comment]
Hi Xuenan, I don't have the possibility to test the skin with IE 11. Could you post a screenshot? How does it look like in IE?

**Comment by pixuenan** [comment]
Hi Thaider,

The problem happens when the window width is smaller than 768px.

Here is the screenshot of it:
![tweeki-1](https://cloud.githubusercontent.com/assets/8290469/20871534/c33a047a-bad1-11e6-8716-5af2c9656973.JPG)

And the style shown in the browser is:

Chrome
![tweeki-chrome](https://cloud.githubusercontent.com/assets/8290469/20871544/e4430068-bad1-11e6-9892-8d74ede04bb6.JPG)

IE 11
![tweeki-ie11](https://cloud.githubusercontent.com/assets/8290469/20871547/ea91b5b8-bad1-11e6-81b1-20f787e0a930.JPG)

In IE 11, the "@media (max_width: 768px).sidebar-wrapper {position: static;}" is missing.

**Comment by thaider** [comment]
Hi Xuenan, sorry for the delay in answering. This is really strange. As mentioned I don't have the possibility to test it but I would gladly accept any patch that you can offer. Could you try to find out more? What happens if you change `position` to `static` manually in the Developer Tools? Could it be problem of the specificity of the styling? What happens if you uncheck the `position: fixed;` line?

Playing around I just found out that there are a few bugs in the implementation also for Firefox (because the breakpoint shouldn't be 768px but rather 992px). I'll try to fix this as soon as possible... Does the layout change when you make the window even smaller than in the screenshot in IE11?
