### ISSUE TITLE
Can the Visual Editor extension be used with Tweeki?

### ISSUE THREAD

**Issue by Tolvic** [thaider/Tweeki#81]
As above.

https://www.mediawiki.org/wiki/VisualEditor
https://www.mediawiki.org/wiki/Extension:VisualEditor

**Comment by thaider** [comment]
Hi Tolvic. In principle, it should be possible. However, as VisualEditor is still in development and therefore a moving target, things can break very easily. I had it working with MW 1.26 and haven't been testing since. Just try it out. You'll need this line LocalSettings.php to make it work:

`$wgVisualEditorSupportedSkins[] = 'tweeki';`

Please share your experiences!

**Comment by Osodarck** [comment]
Thanks for this information @thaider just what I was looking for! Maybe this info should be added to the configuration steps. Visual Editor is working, the only issue is that I'm not able to see the progress bar when the editor is loading. I'll keep on using it and let you know if I find any other issues.

Using last Visual Editor version: 0.1.0

**Comment by thaider** [comment]
Thanks for your feedback, @Osodarck ! I added a paragraph to the How-to page of the documentation. If you have any patches to contribute they're warmly welcome!

**Comment by m-fonseca** [comment]
There is another issue when using the visual editor with pages that require scrolling.  If you scroll down the page, the visual editor toolbar (normally along the top of the screen) scrolls away.   It should stay fixed along the top.

**Comment by thaider** [comment]
Thanks for the comment. As mentioned above, things can break very easily, because Visual Editor's HTML structure and CSS class names are changing from time to time and workarounds won't apply any more. I'm not currently working with Visual Editor in any of my projects so I'm not going to fix this myself – patches are always welcome, however.

**Comment by djflux** [comment]
@m-fonseca @thaider I just added Pull Request https://github.com/thaider/Tweeki/pull/116 which corrects the VE toolbar scrolling (at least for me). Hope this helps someone.

Cheers,
Andy

**Comment by m-fonseca** [comment]
Thank you!  Hopefully I'll get to try it soon.
