### ISSUE TITLE
Width

### ISSUE THREAD

**Issue by aquatiki** [thaider/Tweeki#82]
I think I love this skin more than any other, but the width is killing me.  How can I tweak Tweek to be a little wider?  It looks like it follows the normal columns thingy from bootstrap, but how can I up the main area from 9 to 10 (guess) and perhaps re-up the font size 10%?  Thanks for the amazing skin.

**Comment by thaider** [comment]
Hi. Grid configuration was just fixed in the latest commit. For pages without sidebars you should be able to achieve what you want by putting these lines in your LocalSettings.php:

```
$wgTweekiSkinGridNone = array( 
  "mainoffset" => 0, 
  "mainwidth" => 12 
);
```
If you want to use the full screen width instead of the default 1170px change `MediaWiki:Tweeki-container-class` to `container-fluid`.

I also updated the documentation with further details: http://tweeki.thai-land.at/wiki/How-Tos#Widths

As for the font size: there're many possibilites to achieve that, you could e.g. simply put these lines in `MediaWiki:Common.css`:

```
body {
  font-size:16px;
}
```

The original base font size is 14px and most of the other font sizes should be relative to this size and scale accordingly.

**Comment by aquatiki** [comment]
Thank you so much!!
