### ISSUE TITLE
Header's text not in spans.

### ISSUE THREAD

**Issue by QWITARA** [thaider/Tweeki#84]
In Tweeki skin (even at your own site http://tweeki.thai-land.at/wiki/How-Tos):
<h3><span class="mw-headline" id="Hide_parts_of_the_navigation_on_specific_pages"></span>Hide parts of the navigation on specific pages</h3>

Sould be (and its OK in all other skins):
<h3><span class="mw-headline" id="Hide_parts_of_the_navigation_on_specific_pages">Hide parts of the navigation on specific pages</span></h3>

How to repair?

**Comment by thaider** [comment]
Hi. This is by design. It's a not so beautiful hack that we need, so that when linking to a section the headline will be positioned below a fixed navigation bar and won't be hidden by it. Without the hack the padding and margin settings for `.mw-heading` prevent links directly above the headline from being accessible.

Does the hack break any things for you? What are the unintended consequences?
