### ISSUE TITLE
Removing TOC from sidebar does not revert to default inline TOC

### ISSUE THREAD

**Issue by nickwynja** [thaider/Tweeki#89]
Hi Tobias, I'm looking to use the default MediaWiki inline TOC. I've removed `TOC` from `MediaWiki:Tweeki-sidebar-right` and the skin is not defaulting to the standard inline TOC.

How can I set up Tweeki to have the TOC inline with the content as it behaves in Vector?

**Comment by thaider** [comment]
Hi. Thanks for the report. The TOC is hidden by default, you'll just have to make it visible by adding these lines to your custom stylings:

```
#toc {
  display:block;
}
```

I also wrote a short [How-To](http://tweeki.thai-land.at/wiki/How-Tos#Standard_Table_Of_Contents) for the documentation. Please note that you'll need to update Tweeki to the latest revision in order to not have the sidebar styles being applied to the TOC. You'll also have to add your own styles to make it look nicer.
