### ISSUE TITLE
Tweeki seems to be too invasive

### ISSUE THREAD

**Issue by kghbln** [thaider/Tweeki#91]
**Setup**
- MediaWiki 	1.29.0-rc.0 (37c22fc) 23:03, 22 June 2017
- PHP 	5.6.30-0+deb8u1 (apache2handler)
- MariaDB 	10.0.31-MariaDB-1~jessie
- Tweeki	0.1.4 (c116315) 21:30, 12 April 2017

**Issue**
Messages like "tweeki-editsection-text" seem to override core MediaWiki system messages "editsection" even though the skin is not selected as the user's standard skin. If "Tweeki" is meant to be a "me only skin" - which is fine with me - the message should at least be localized instead of being [empty](https://github.com/thaider/Tweeki/blob/master/i18n/en.json#L35).

**Comment by thaider** [comment]
Thanks for the report, @kghbln. I fixed this and made it optional via `$wgTweekiSkinCustomEditSectionLink` configuration setting (`true` by default).

The message being empty is intentional the default behavior being to only show the pencil icon (that can be changed via it's own message). The documentation was outdated and has been [amended](http://tweeki.thai-land.at/wiki/Changelog).

**Comment by kghbln** [comment]
Great, thanks a lot - also for the explanation. Just updated to current master and it works.
