### ISSUE TITLE
Tweeki-right-sidebar not working properly with dynamic content

### ISSUE THREAD

**Issue by Jatin1697** [thaider/Tweeki#94]
**Setup** 

- MediaWiki : 1.28.2.
- Semantic mediawiki 2.5.2
- PHP 7.1.1

**Issue**
- The dynamic content which does not contain heading also shown in tweeki-right-sidebar.
- One of the section remains active in the right sidebar and others do not even collapse down.
- How to hide some content to be shown on the right sidebar?

**Comment by thaider** [comment]
Hi,

I don't fully understand the issue. Could you please elaborate a bit or provide some screenshots? If you're refering to headings that are shown in the table of contents, one way to hide some of the headings is to use `<div>` tags instead of the heading tags and use css classes for stylings that mimic the other headings.

**Comment by Jatin1697** [comment]
Hey,

Actually wiki was showing random behaviour when i was mis-aligning the divs
in the center. Now, I know should pull them left and its working.

I was using the heading tag for most of the contents, that might be the
issue of their showing the it the right-side-bar.

Thaks for replying .
Now you can close the issue.
