### ISSUE TITLE
Remote CSS files

### ISSUE THREAD

**Issue by lifehome** [thaider/Tweeki#95]
May I know how to load both Bootstrap and FontAwesome from CDN URL instead of local files?

**Comment by thaider** [comment]
This is maybe more of an MediaWiki issue. Since MediaWiki doesn't provide obvious mechanisms to do what you want it probably won't be implemented for Tweeki. I'd happily accept any working patches that you can provide, however. Maybe you can achieve what you want by using one of [`OutputPage`](https://www.mediawiki.org/wiki/Manual:OutputPage.php)'s functions (addScript, addStyle, addHeadItem)?
